project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('timetracking_app.urls'))
]

project/timetracking_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (HomePageView, LoginView, AddHoursView, ViewDepartmentHoursView,
                    ViewEmployeesHoursView, AddEmployeeView, LogoutView, ListAllHoursView, HoursPerChannelView,
                    DeleteHoursView, EditHoursView, EditEmployeeView, DeactivateEmployeeView, ResetPasswordView,
                    SearchEmployeeView, EmployeeDetailView)

urlpatterns = [
    path('home/', HomePageView.as_view(), name='home-page'),
    path('login/', LoginView.as_view(), name='login-page'),
    path('logout/', LogoutView.as_view(), name='logout-page'),
    path('add_hours/', AddHoursView.as_view(), name='add-hours'),
    path('list_all_hours/', ListAllHoursView.as_view(), name='list-all-hours'),
    path('channel_hours/', HoursPerChannelView.as_view(), name='hours-per-channel'),
    path('department_hours/', ViewDepartmentHoursView.as_view(), name='department-hours'),
    path('employees_hours/', ViewEmployeesHoursView.as_view(), name='employees-hours'),
    path('add_employee/', AddEmployeeView.as_view(), name='add-employee'),
    path('delete_hours/<int:pk>/', DeleteHoursView.as_view(), name='delete-hours'),
    path('edit_hours/<int:pk>/', EditHoursView.as_view(), name='edit-hours'),
    path('edit_employee/<int:pk>/', EditEmployeeView.as_view(), name='edit-employee'),
    path('deactivate_employee/<int:pk>/', DeactivateEmployeeView.as_view(), name='deactivate-employee'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('search_employee/', SearchEmployeeView.as_view(), name='search-employee'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'), name='change-password'),
    path('change_password_done/', auth_views.PasswordChangeView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    path('employee_details/<int:pk>/', EmployeeDetailView.as_view(), name='employee-detail'),
]

project/timetracking_app/models.py
from datetime import datetime

from django.contrib.auth.models import User, AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.


class Person(AbstractUser):
    email = models.EmailField(unique=True)
    department = models.ForeignKey('Department', related_name='persons_department', on_delete=models.CASCADE, null=True)
    sales_channels = models.ManyToManyField('SalesChannel')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return f"{self.username}, {self.first_name}, {self.last_name}, {self.email}"


class Department(models.Model):
    department_name = models.CharField(max_length=64, unique=True)
    manager = models.ForeignKey(Person, related_name='department_manager', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.department_name}'


class SalesChannel(models.Model):
    channel_name = models.CharField(max_length=64, unique=True)
    department = models.ManyToManyField(Department)

    def __str__(self):
        return f'{self.channel_name}'


class LoggedHours(models.Model):
    date = models.DateField(null=True)
    hour = models.FloatField(validators=(MinValueValidator(0.25), MaxValueValidator(8)))
    employee = models.ForeignKey(Person, on_delete=models.CASCADE)
    sales_channel = models.ForeignKey(SalesChannel, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.date}, {self.hour}, {self.employee}, {self.sales_channel}'

project/timetracking_app/forms.py
from datetime import datetime, timedelta

from django import forms
from django.forms import PasswordInput
from django.core.exceptions import ValidationError

from .models import SalesChannel, LoggedHours, Department, Person


class LoginForm(forms.Form):
    # username = forms.CharField(label='login', max_length=64)
    email = forms.EmailField(label='email')
    password = forms.CharField(label='password', max_length=64, widget=PasswordInput)


class AddHoursForm(forms.ModelForm):
    employee = forms.ModelChoiceField(queryset=Person.objects.all(), widget=forms.HiddenInput(), required=False)
    class Meta:
        model = LoggedHours
        fields = ['date', 'sales_channel', 'department', 'hour']
        widgets = {'date': forms.DateInput(format=('%Y/%d/%m'), attrs={'placeholder': 'Select a date', 'type': 'date'})}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Pobierz użytkownika przekazanego do formularza
        super().__init__(*args, **kwargs)
        if user:
            # Jeśli użytkownik jest dostępny, ustaw jego wartość dla pola employee
            self.initial['employee'] = user
            # Ukryj pole employee w formularzu
            self.fields['employee'].widget = forms.HiddenInput()
        self.fields['sales_channel'].queryset = SalesChannel.objects.all()
        self.fields['department'].queryset = Department.objects.all()


    def clean_date(self):
        date = self.cleaned_data['date']
        if date > date.today():
            raise ValidationError ('The date cannot be in the future.')
        elif date < date.today() - timedelta(days=30):
            raise ValidationError(f"The date must be within last 30 days.")
        return date


class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label='Email')
    new_password = forms.CharField(label='New password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirm new password', widget=forms.PasswordInput)


class SearchEmployeeForm(forms.Form):
    email = forms.EmailField(label='Email', required=False)
    first_name = forms.CharField(label='First name', required=False)
    last_name = forms.CharField(label='Last name', required=False)
    department = forms.CharField(label='Department', required=False)


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput)
    new_password = forms.CharField(label='New password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirm new password', widget=forms.PasswordInput)

project/timetracking_app/views.py
import sendgrid
import os

from sendgrid.helpers.mail import *

from django.utils import timezone
from django.utils.timezone import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission, Group
from django.contrib.auth.views import LoginView
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import send_mail
from django.http import HttpResponse, QueryDict
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import FormView, ListView, DeleteView, UpdateView, CreateView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from django.conf import settings

from .forms import AddHoursForm, LoginForm, ResetPasswordForm, SearchEmployeeForm
from .models import LoggedHours, SalesChannel, Person, Department


#Create a parent class with methods that will be reused in the code.
class DateFilterView(View):

#Setting up query strings to be used for filtering data
    def set_up_query_strings(self, *args, **kwargs):
        query_params = QueryDict(mutable=True)
        #Setting up query parameters
        query_params['filter_type'] = 'value'

        # Redirecting to the selected page dependent on selected parameter
        redirect_url = '/channel_hours/?' + query_params.urlencode()
        return redirect_url

#Filtering based on specified timeframes (weekly, monthly, yearly or without any filter)
    def filter_by_dates_range(self, filter_type):
        #filter 'weekly'
        if filter_type == 'weekly':
            all_entries = LoggedHours.objects.filter(date__gte=timezone.now(),
                                                     date__lte=timezone.now() + timedelta(days=6))
            return all_entries
        # filter 'monthly'
        elif filter_type == 'monthly':
            all_entries = LoggedHours.objects.filter(date__gte=timezone.now().replace(day=1).strftime('%Y-%m-%d'))
            return all_entries
        # filter 'yearly'
        elif filter_type == 'yearly':
            all_entries = LoggedHours.objects.filter(
                date__gte=timezone.now().replace(day=1, month=1).strftime('%Y-%m-%d'))
            return all_entries
        # no date filter - all data
        else:
            all_entries = LoggedHours.objects.all()
            return all_entries


#Home page - visible to logged in users only.
class HomePageView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        return render(request, 'base.html')

#Login page + redirection to login from restricted views
class LoginView(FormView):
    template_name = 'login_form.html'
    form_class = LoginForm
    success_url = reverse_lazy('home-page')

    def form_valid(self, form):
        # username = form.cleaned_data['username'] #fetch login
        email = form.cleaned_data['email']
        password = form.cleaned_data['password'] #fetch password
        user = authenticate(username=email, password=password) #authenticate user

        #if user is aythenticated - log them in
        if user is not None:
            login(self.request, user)
            return redirect(self.get_success_url())
        #return the form with the error message to the users that did not successfully login
        else:
            return render(self.request, self.template_name,  {'user': user, 'form': form, 'error_message': 'Login error.'})

#Logout the user, display a message
class LogoutView(View):
    def get(self, request):
        user = request.user
        logout(request)
        return render(request, 'logout_page.html',  {'user': user, 'message': 'logged out successfully.'})

#Add hours of a logged in user to the database.
class AddHoursView(LoginRequiredMixin, FormView):
    login_url = '/login/'
    template_name = 'add_hours.html'
    form_class = AddHoursForm
    success_url = reverse_lazy('list-all-hours')


    def form_valid(self, form):
        # Fetch info about the user
        user = self.request.user

        # Create add hours form, prefill the user data and let the user fill in the ramining details
        form = form
        form.fields['employee'].initial = user
        date = form.cleaned_data['date']
        form_sales_channel = form.cleaned_data['sales_channel']
        form_department = form.cleaned_data['department']
        sales_channel = get_object_or_404(SalesChannel, channel_name=form_sales_channel)
        department = get_object_or_404(Department, department_name=form_department)
        hour = form.cleaned_data['hour']

        #Add hours to the database
        employee_hours = LoggedHours.objects.create(date=date, hour=hour, employee=user, sales_channel=sales_channel, department=department)

        return super().form_valid(form)


#Display all hours added by a logged in user.
class ListAllHoursView(LoginRequiredMixin, ListView, DateFilterView):
    login_url = '/login/'
    model = LoggedHours
    success_url = '/list_all_hours/'
    template_name = 'list_hours.html'
    context_object_name = 'employee_entries'
    paginate_by = 10
    ordering = ['sales_channel']

    def get_queryset(self):
        user = self.request.user
        queryset = LoggedHours.objects.filter(employee=user)
        queryset = self.filter_by_dates_range(queryset)
        return queryset

    # filter data dependent on dates range
    def filter_by_dates_range(self, queryset):
        filter_type = self.request.GET.get('filter_type')
        if filter_type == 'weekly':
            start_date = timezone.now() - timezone.timedelta(days=7)
        elif filter_type == 'monthly':
            start_date = timezone.now() - timezone.timedelta(days=30)
        elif filter_type == 'yearly':
            start_date = timezone.now() - timezone.timedelta(days=365)
        else:
            # Default: no filtering
            return queryset

        return queryset.filter(date__gte=start_date)

    # summarize data per channel and dates range selected by user
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_type = self.request.GET.get('filter_type')
        # apply filter by date
        context['filter_type'] = filter_type
        # get queryset
        all_entries = self.get_queryset()


        # get context data to the filtering buttons
        context['weekly'] = self.set_up_query_strings('weekly')
        context['monthly_url'] = self.set_up_query_strings('monthly')
        context['yearly_url'] = self.set_up_query_strings('yearly')

        return context


#Allow access to view summarised hours per sales channel to logged in users with specified permissions.
class HoursPerChannelView(LoginRequiredMixin, PermissionRequiredMixin, ListView, DateFilterView):
    login_url = '/login/'
    permission_required = ['timetracking_app.view_hours_per_channel']

    model = LoggedHours
    fields = '__all__'
    template_name = 'channel_hours.html'
    context_object_name = 'logged_hours'

    #Filter queryset dependent on the user group.
    def get_queryset(self):
        user = self.request.user

        # restricting data visibility - managers can view their departments only, director can view all departments
        if user.groups.filter(name='director_user').exists():
            queryset = LoggedHours.objects.all()
        elif user.groups.filter(name='manager_user').exists():
            queryset = LoggedHours.objects.filter(department=user.department)

        else:
            queryset = LoggedHours.objects.all()

        queryset = self.filter_by_dates_range(queryset)
        return queryset

    #filter data dependent on dates range
    def filter_by_dates_range(self, queryset):
        filter_type = self.request.GET.get('filter_type')
        if filter_type == 'weekly':
            start_date = timezone.now() - timezone.timedelta(days=7)
        elif filter_type == 'monthly':
            start_date = timezone.now() - timezone.timedelta(days=30)
        elif filter_type == 'yearly':
            start_date = timezone.now() - timezone.timedelta(days=365)
        else:
            # Default: no filtering
            return queryset

        return queryset.filter(date__gte=start_date)

    #summarize data per channel and dates range selected by user
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_type = self.request.GET.get('filter_type')
        #apply filter by date
        context['filter_type'] = filter_type
        #get queryset
        all_entries = self.get_queryset()

        #summarize hours per channel (of all users)
        hours_per_channel = {}
        for entry in all_entries:
            sales_channel = entry.sales_channel
            hours = entry.hour
            if sales_channel in hours_per_channel:
                hours_per_channel[sales_channel] += hours
            else:
                hours_per_channel[sales_channel] = hours
        context['hours_per_channel'] = hours_per_channel

        #calling function that sets up the context data for charts
        labels_data = self.get_labels_data(all_entries)
        context.update(labels_data)

        #get context data to the filtering buttons
        context['weekly'] = self.set_up_query_strings('weekly')
        context['monthly_url'] = self.set_up_query_strings('monthly')
        context['yearly_url'] = self.set_up_query_strings('yearly')

        return context

    #structure the context data for the charts
    def get_labels_data(self, logged_hours):
        labels = []
        data = []

project/timetracking_app/templates/all_employees_hours.html
{% extends 'list_hours.html' %}
{% block title %} All employees hours{% endblock %}
{% block content %}


{% if perms.timetracking_app.view_hours_per_channel %}
    <table>
        <tr>
        <th>Person</th>
        <th> Date </th>
        <th> Sales channel </th>
        <th> Hours </th>
            <th> ---</th>
        </tr>
        {% for entry in employee_entries %}


        <tr>
       <td>{{ entry.employee.username }}</td>
       <td> {{ entry.date }} </td>
       <td> {{ entry.sales_channel }} </td>
       <td> {{ entry.hour }}</td>
        <td>
            {% if perms.timetracking_app.change_hours %}
           <a href="{% url 'edit-hours' pk=entry.id %}"> <button type="submit" value="edit_hours">Edit</button> </a>
            {% endif %}
            {% if perms.timetracking_app.delete_hours %}
           <a href="{% url 'delete-hours' pk=entry.id %}"> <button type="submit" value="delete_hours">Delete</button> </a></td>
            {% endif %}

        </tr>
{% endfor %}
<br>
        </table>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<br>
   <table border="1">
      {% for employee, hours in hours_per_employee.items %}
          <tr>
          <th> Employee </th>
              <th> Hours </th>
          </tr>
          <tr>
              <td> {{ employee.username }}</td><td> {{ hours }}</td>
          </tr>
      {% endfor %}
</table>
    {% else %} You don't have permissions to view this site.
    {% endif %}




{% endblock %}

{% block footer %} {% endblock %}

project/timetracking_app/templates/base.html
{% load static %}



<!doctype html>
<html>
   {% block head %}
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} Home {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <!-- Core theme CSS (includes Bootstrap)-->
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    </head>
    {% endblock %}

{% block body %}
    <body>
         <div class="d-flex" id="wrapper">

            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                {% if user.is_authenticated %}

                <div class="sidebar-heading border-bottom bg-light">Timetracker</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'add-hours' %}">Log hours</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'list-all-hours' %}">View hours</a>
                     {%  if perms.timetracking_app.view_hours_per_channel %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'hours-per-channel' %}">Hours per channel</a>
                     {% endif %}
                    {%  if perms.timetracking_app.view_hours_per_department %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'department-hours' %}">Hours per department</a>
                     {% endif %}
                    {%  if perms.timetracking_app.view_hours_per_employee %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'employees-hours' %}">All employees' hours</a>
                     {% endif %}
                    {% if perms.timetracking_app.add_person %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'add-employee' %}">Add employee</a>
                        {% endif %}
                </div>
                {% endif %}
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        {% if user.is_authenticated %}
{#                        <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>#}
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item active"><a class="nav-link" href="{% url 'home-page' %}">Hello {{ user.first_name }}!</a></li>
                                <li class="nav-item dropdown">
                                <li class="nav-item active"><a class="nav-link" href="{% url 'home-page' %}">Home</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'add-hours' %}">Log hours </a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'search-employee' %}">Search employee </a>
                                        <div class="dropdown-divider"></div>
                                        {% if user.is_superuser %}
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">Administration panel </a>
                                        <div class="dropdown-divider"></div>
                                        {% endif %}
                                        <a class="dropdown-item" href="{% url 'change-password' %}">Change password </a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'logout-page' %}">Logout</a>
                                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    </div>
                                </li>
                            </ul>
                        </div>
                        {% endif %}

                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    <h1 class="mt-4">
                        {% if user.is_authenticated %}
                        {% endif %}
                    </h1>
                    {% if user.is_authenticated %}
                    <p> </p>
                    {% endif %}
                {% endblock %}

                    <p>
                        <code>{% block content %} {% endblock %}</code>
                        <code>{% block footer %} {% endblock %}</code>
                    </p>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

    </body>
</html>

project/timetracking_app/templates/base2.html
{% load static %}



<!doctype html>
<html>
    {% block head %}
    <head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


            <img src="{% static 'logo.png' %}" alt="Fake company logo" align="right">
            <a href="{% url 'home-page' %}"><button type="submit">Home</button></a>


            {% if user.is_authenticated %}
            Hello, {{ user.username | title }}!
            {% endif %}
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    </head>
    {% endblock %}

    <title> {% block title %} Home {% endblock %}</title>

    <body>
        <h1>Timetracker</h1>
        {% block content %}

            <strong> Log hours </strong>
       <p> <a href="{% url 'add-hours' %}"><button type="submit">Log hours</button></a></p>
            <p><strong> View your hours </strong></p>

        <p><a href="{% url 'view-hours' %}"><button type="submit">View your hours</button></a></p>
         <p><strong> View summarised hours </strong></p>

        <p>
        <a href="{% url 'hours-per-channel' %}"><button type="submit">Channel hours</button></a>
        <a href="{% url 'department-hours' %}"><button type="submit">Department hours</button></a>
        <a href="{% url 'employees-hours' %}"><button type="submit">Employees' hours</button></a>
        </p>
            <p><strong> Manage users </strong></p>

            <p><a href="{% url 'add-employee' %}"><button type="submit">Add employee</button></a></p>
{#        <a href="{% url '' %}"><button type="submit">Edit empl (to be) </button></a><br>#}

        {% endblock %}


    {% block footer %}    <a href="{% url 'logout-page' %}"><button type="submit">Logout</button></a>

            {{ user.username | title}}
        {% endblock %}

    <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

project/timetracking_app/templates/deactivate_employee.html
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        The user will be deactivated. Press OK to complete the deactivation process.

        <input type="submit" value="OK">
    </form>

project/timetracking_app/templates/employee_detail.html
{% extends 'base.html' %}

{% block title %} Employee {% endblock %}
{% block content %}

{# <table border="1">#}
{#        <tr>#}
{#            <th>Id</th>#}
{#            <th>Username</th>#}
{#            <th>First name </th>#}
{#            <th>Last name </th>#}
{#            <th>Department </th>#}
{##}
{#        </tr>#}
{##}
{#                <tr>#}
{#                    {% for employee in employees %}#}
{#                    {% if employee.is_active %}#}
{#                    <td >{{ employee.id }}</td>#}
{#                    <td>{{ employee.username }}</td>#}
{#                    <td>{{ employee.first_name }}</td>#}
{#                    <td>{{ employee.last_name }}</td>#}
{#                    <td>{{ employee.department }}</td>#}
{#                </tr>#}
{#                    {% endif %}#}
{#                    {% endfor %}#}
{#    </table>#}

{% if employees %}

{% for employee in employees %}
    {% if employee.is_active %}
<li> Id: {{ employee.id  }}<br> Email: {{ employee.email }}<br> Name: {{ employee.first_name }}<br> Surname: {{ employee.last_name }}<br>
    Department: {{ employee.department }} <br>
    {% if perms.timetracking_app.change_person %}
    <a href="{% url 'edit-employee' pk=employee.id %}"> <button type="submit" value="update_person">Edit</button> </a></td>
        {% endif %}
    {% if perms.timetracking_app.delete_person %}
    <a href="{% url 'deactivate-employee' pk=employee.id %}"> <button type="submit" value="delete_person">Deactivate</button> </a></td>
        {% endif %}

</li>
    {% endif %}
{% endfor %}

{% else %}
        There are no users matching your search criteria.
{% endif %}




{% endblock %}

{% block footer %} {% endblock %}

project/timetracking_app/templates/employee_full_details.html
{% extends 'base.html' %}

{% block title %} Employee hours {% endblock %}
{% block content %}

{# <table border="1">#}
{#        <tr>#}
{#            <th>Id</th>#}
{#            <th>Username</th>#}
{#            <th>First name </th>#}
{#            <th>Last name </th>#}
{#            <th>Department </th>#}
{##}
{#        </tr>#}
{##}
{#                <tr>#}
{#                    {% for employee in employees %}#}
{#                    {% if employee.is_active %}#}
{#                    <td >{{ employee.id }}</td>#}
{#                    <td>{{ employee.username }}</td>#}
{#                    <td>{{ employee.first_name }}</td>#}
{#                    <td>{{ employee.last_name }}</td>#}
{#                    <td>{{ employee.department }}</td>#}
{#                </tr>#}
{#                    {% endif %}#}
{#                    {% endfor %}#}
{#    </table>#}

{% if employee %}

    {% if employee.is_active %}
<li> Id: {{ employee.id  }}<br>
    Email: {{ employee.email }}<br>

    Active: {{ employee.is_active}} <br>
    Staff: {{ employee.is_staff }} <br>
    Hours:
    {% for entry in employee_entries %}
        <li>{{ entry.date }} - {{ entry.department }} - {{ entry.sales_channel }} - {{ entry.hour }} hour(s) </li>

    {% empty %}
        No logged hours found.
    {% endfor %}



    {% endif %}

{% else %}
        There are no users matching your search criteria.
{% endif %}




{% endblock %}

{% block footer %} {% endblock %}

project/timetracking_app/templates/list_people.html
{% extends 'list_hours.html' %}
{% block title %} All employees hours{% endblock %}
{% block content %}



<ol>
{% for employee in employee_entries %}
    {% if employee.is_active %}
<li> {{ employee.id }}{{ employee.username }}
    {% if perms.timetracking_app.change_person %}
    <a href="{% url 'edit-employee' pk=employee.id %}"> <button type="submit" value="update_person">Edit</button> </a></td>
        {% endif %}
    {% if perms.timetracking_app.delete_person %}
    <a href="{% url 'deactivate-employee' pk=employee.id %}"> <button type="submit" value="delete_person">Deactivate</button> </a></td>
        {% endif %}

</li>
    {% endif %}
{% endfor %}
</ol>



{% endblock %}

{% block footer %} {% endblock %}

project/timetracking_app/templates/person_update_form.html
{% extends 'form.html' %}